name: Nina

on:
  push:
    branches: main
      
jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # add secrets in github repository settings
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - 
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 590183817831.dkr.ecr.us-east-1.amazonaws.com # change region and account id
      - 
        name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: 590183817831.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: nina-ecr # ECR repository name
          IMAGE_TAG: latest
        run: |
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            echo "NUTRITIONIX_APP_ID=${{ secrets.NUTRITIONIX_APP_ID }}" >> .env
            echo "NUTRITIONIX_API_KEY=${{ secrets.NUTRITIONIX_API_KEY }}" >> .env

            docker build . -f ./Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
            docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
            echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"

            echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV
            echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV